version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - CLTV
  - CUFG
  - CUNA
  - DIVI
  - easyaccordion
  - Gilmer
  - ITIN
  - Marshinick
  - NCUA
  - NMLS
  - Telco
  - TPCU
  - Watercrafts
  - Weese
ignoreWords: []
import: []
